app: apigw-oauth-flask-app
stage: dev
component: flask
name: flaskInstance
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: .
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Python3.6
  functionConf:
    eip: false
    timeout: 3
    memorySize: 128
  apigatewayConf:
    serviceTimeout: 60
    protocols:
      - http
      - https
    environment: release
    autoCreateDns: false
  isAutoCiDeploy: true
  codePlatform: GITHUB
